### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by Denrage** [jwueller/jellyfin-plugin-onepace#28]
Currently trying to integrate One Pace into Jellyfin, and its not working as i would expect.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/22132579/c9a24c2e-b3fb-4031-87f5-734319816b78)
It creates multiple times the same episodes

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/22132579/b04d1998-6aac-4c67-a5e5-2c71d0e8d9ab)
It puts episodes from other arcs into the wrong arcs

[Log.txt](https://github.com/jwueller/jellyfin-plugin-onepace/files/12466783/Log.txt)

Folder Structure
"One Pace/One Pace/[One Pace][1-7] Romance Dawn/[One Pace][001] Romance Dawn 01 [1080p][FB72C13F].mkv"

If you need anything else, i'm happy to help. If you can tell me how to debug the plugin myself, i can dig into it for you

**Comment by jwueller** [comment]
Thanks for reporting this, I'll try and see if I can figure out the root cause and maybe make it less likely for the plugin to generate false-positive matches in the future.
