### ISSUE TITLE
[Question] How does this handle incomplete arcs?  Like Arabasta?

### ISSUE THREAD

**Issue by Kylar514** [jwueller/jellyfin-plugin-onepace#30]
Basically, Arabasta is not complete by onepace...  How does this handle that?  Simply ignores?  Takes the full episodes and just throws them in?

**Comment by jwueller** [comment]
It doesn't, really. The main issue is that there isn't an easy way to sort them in between the One Pace episodes in a consistent way. It basically depends on how Jellyfin decides to handle files the plugin can't identify.
