### ISSUE TITLE
Jaya and Post Enies Lobby Arcs Missing

### ISSUE THREAD

**Issue by mzrimsek** [jwueller/jellyfin-plugin-onepace#44]
Basically the title. I updated recently because I read it fixed some issues I was noticing where the episodes wouldn't be listed under an arc.

After updating 2 of the arcs seem to be missing (I count 30 when there should be 32 so it seems to just be these 2).

**Comment by jwueller** [comment]
Hi! Can you confirm that you are running on the latest version? It should be 1.4.0.0.

Chapter ranges are the most reliable way to do the matching, but the titles should work as well. Please feel free to reopen this if the issue persists on the latest version! In that case it would be very helpful if you could upload the relevant logs.

**Comment by mzrimsek** [comment]
Yep I updated to the latest version last night I need to add the chapter ranges to my folders later today and see if that fixes it. If I run into any issues I'll try to upload anything relevant to try and track down what's going on!

**Comment by jwueller** [comment]
The new version should work with just the titles too. That's why I'm concerned that it might not actually work as intended. You can work around it with the chapter ranges though.

**Comment by mzrimsek** [comment]
Gotcha. FWIW this is what my current naming looks like (apologies I'm not at my home computer with easy access to a better file explorer)

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/10595301/ee71184f-59f9-4f56-ab63-891063d37071)

**Comment by jwueller** [comment]
That's very helpful, thanks! I'll try and see if I can reproduce this problem locally.

**Comment by mzrimsek** [comment]
I will also add that before updating I believe it was listing all the arcs as seasons properly (though no way to easily verify this atm). I had taken a small break from the show after getting through Arabasta and noticed when trying to load up Jaya that no episodes were listed even though it had the number showing correctly (which is what I believe y'all fixed in the latest update).

I'd be happy to downgrade (if that's possible) to try and help troubleshoot this later once I am back from work though.

**Comment by mzrimsek** [comment]
Alright I had a chance to look at this again. I renamed my folders and stuff did improve a bit but it seems maybe there are some issues. Here is how I have it named now - perhaps a second pair of eyes will spot anything I messed up if I did.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/10595301/79ef4bde-aae0-4192-86dc-10d1910afa63)

After rescanning my library a lot of arcs that were missing their art now have it which is sick. Love that. I do notice that Gaimon arc looks different like it's the default art of the plugin so I feel like I probably did something wrong with how I named the folder but it seems to have all the content and whatever all fine.

My list seems to have the Skypiea and Jaya arcs in the wrong order (just swapped it looks like?). It also looks like the Post-Enies Lobby arc is missing, but again maybe I misnamed something.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/10595301/d503c103-d011-4d02-bc31-88b9618c63dd)

Lemme know if there's anything I should change or if there's anything else I can share to help if these are in fact issues that aren't just user error on my end.

**Comment by mzrimsek** [comment]
Upon further investigation I am seeing the episodes from the Long Ring Long Land arc in my Jaya arc. They seem to be listing then mixed together - 1 episode of Long Ring Long Land, 1 episode of Jaya.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/10595301/c554f987-c582-40f9-8ef6-3838618e7685)

Something similar seems to be going on with Enies Lobby. My arc has all the episodes of Enies Lobby and then instead of having another arc for Post-Enies Lobby, all the Post-Enies Lobby episodes are just listed under Enies Lobby starting after the last episode of that arc.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/10595301/e519542a-9465-4caa-b0fd-5cac361ca07c)

I'm not sure if I did something with my naming or if this is a bug in the plugin.

**Comment by mzrimsek** [comment]
I'm not sure what changed but on a whim today I decided to reload all the metadata for One Pace and it seems to have fixed itself? I didn't change anything since last I commented here so genuinely not sure what changed but I'm not gonna argue with it!

Thanks again for making this wonderful Jellyfin plugin!

**Comment by jwueller** [comment]
I was trying to reproduce this and failed, so maybe this was just Jellyfin keeping some old data around after all. Thanks for your testing and feedback! Please feel free to reopen this if you encounter the issue again!

**Comment by mzrimsek** [comment]
I appreciate you looking into it for me even if it was a wild goose chase!
