### ISSUE TITLE
Seasons in alphabetical order & Enies merging

### ISSUE THREAD

**Issue by belyr** [jwueller/jellyfin-plugin-onepace#6]
Hi! Love the plugin, really made organizing this beast of a show easy!

I've come across an issue lately where the seasons after the first one are showing in alphabetical order rather than proper order. The arcs for Enies Lobby and Post-Enies Lobby appear to have merged together as well. (notice 30 files for Enies Lobby in the screenshot)

I have tried renaming the arcs folders to both [Arc 01 - Romance Dawn] and [Season 01 - Romance Dawn] with no success.

Any idea what could be causing this?

![chrome_IqfCGLIVed](https://user-images.githubusercontent.com/104872972/224460314-7f6e0ae3-6e0a-49f0-9e83-b58c9bd0c939.png)

**Comment by jwueller** [comment]
That's a very interesting result I haven't seen before. Could you share what your exact directory/file structure looks like? Also, can you check which version of the plugin you are using? The most recent Version is v1.0.2.0 and already contains a few fixes compared to the initial release.

**Comment by belyr** [comment]
Hi! My apologies for the lack of response, I forgot I had made this post.

My file structure is the recommended one on the main page and I am running the latest plugin version. I ended up deleting and recreating my library, and that ultimately fixed the ordering issue, but Enies Lobby and Post-Enies are still merged. (not nearly as big of a deal as the ordering, I can live with a combined season)

**Comment by jwueller** [comment]
Thanks for getting back to me!

Could you make sure that you're replacing the metadata using the latest version? I fixed a similar issue in release v1.0.2.0 (6f71b85d7a814c333cf785dff2bf629c0739bbf9).

If the issue persists, it would still be very helpful to see the exact filenames you have to figure out why the seasons get assigned incorrectly.

**Comment by jwueller** [comment]
I'll assume that this has been resolved, feel free to reopen if this is still a problem!
