### ISSUE TITLE
How to deal with non released OnePace episodes? 

### ISSUE THREAD

**Issue by pedrety** [jwueller/jellyfin-plugin-onepace#7]
Is there any way to put them in the arc folders without making a mess? I tried to put, for example, Baratie and all the manual episodes were messed up. 

This is the file structure:

```
[One Pace][42-59] Baratie 1-6 [1080p]
├── [One Pace][42-44] Baratie 01 [1080p][CC37D6C6].mkv
├── [One Pace][45-47] Baratie 02 [1080p][FCF3D074].mkv
├── [One Pace][47-49] Baratie 03 [1080p][0EB7F7E9].mkv
├── [One Pace][50-52] Baratie 04 [1080p][15D77CB3].mkv
├── [One Pace][53-55] Baratie 05 [1080p][6858E16A].mkv
├── [One Pace][56-59] Baratie 06 [1080p][757AF173].mkv
├── [One Pace][59-63] Baratie 07 [1080p].avi
├── [One Pace][63-67] Baratie 08 [1080p].avi
├── [One Pace][67-68] Baratie 09 [1080p].avi
└── [One Pace][68] Baratie 10 [1080p].avi
```

From 07-10 are manual downloaded episodes, so the manga ID is not really relevant, but in this case as there are more manual episodes than the OnePace remaining for this arc. So, what am I suppose to do with those episodes? Which names should I put them?

**Comment by jwueller** [comment]
I'm sorry, I somehow missed this issue as I'm currently on vacation.

I didn't try to deal with this particular problem yet, as I'm not doing it that way myself, but I'll try and see if I can come up with something.

Maybe it's possible to delegate those episodes to the regular resolver mechanism, but it will be tricky to get a coherent result. A One Pace episode will usually span multiple Anime episodes, but not necessarily sequentially, so there isn't really a well-defined order for mixed episode types. It might be possible to get close though.

**Comment by pedrety** [comment]
I manage to resolve this by naming the episodes not released yet with the Jellyfin default name format.

To clarify, this is the format I'm following now:

```
[One Pace][42-59] Baratie 1-6 [1080p]
├── [One Pace][42-44] Baratie 01 [1080p][CC37D6C6].mkv
├── [One Pace][45-47] Baratie 02 [1080p][FCF3D074].mkv
├── [One Pace][47-49] Baratie 03 [1080p][0EB7F7E9].mkv
├── [One Pace][50-52] Baratie 04 [1080p][15D77CB3].mkv
├── [One Pace][53-55] Baratie 05 [1080p][6858E16A].mkv
├── [One Pace][56-59] Baratie 06 [1080p][757AF173].mkv
├── Episode S05E07.avi
├── Episode S05E08.avi
├── Episode S05E09.avi
└── Episode S05E10.avi
```

The last 4 episodes are sorted as expected. Not a fancy solution but it makes the trick . Hope you get to a solution, but for now if someone is experiencing the same problem they can fix it this way 😸

**Comment by jwueller** [comment]
Alright, it seems Jellyfin falls back to the default resolver when the plugin doesn't claim it for itself. Good to know! Thanks for posting your workaround!

I'll close this as I don't really see anything other than delegation to the default resolver making much sense right now.
