### ISSUE TITLE
Can't seem to play media while using plugin

### ISSUE THREAD

**Issue by ReinT0** [jwueller/jellyfin-plugin-onepace#9]
When I have my One Pace media in a library it wont play, getting errors (see screenshots below), when moving them to another folder with a different library they play just fine. This is my file structure:

```
/media/One Pace/
├── [One Pace][1-7] Romance Dawn [1080p]
│   ├── [One Pace][1] Romance Dawn 01 [1080p][FB72C13F].mkv
│   ├── [One Pace][2] Romance Dawn 02 [1080p][667784D2].mkv
│   ├── [One Pace][3-5] Romance Dawn 03 [1080p][F5E73C4E].mkv
│   └── [One Pace][5-7] Romance Dawn 04 [1080p][9A48E3EB].mkv
├── ...
├── ...
├── [One Pace][8-21] Orange Town [1080p]
│   ├── [One Pace][42-44] Baratie 01 [1080p][CC37D6C6].mkv
│   ├── [One Pace][45-47] Baratie 02 [1080p][FCF3D074].mkv
│   ├── [One Pace][47-49] Baratie 03 [1080p][0EB7F7E9].mkv
│   ├── [One Pace][50-52] Baratie 04 [1080p][15D77CB3].mkv
│   ├── [One Pace][53-55] Baratie 05 [1080p][6858E16A].mkv
│   └── [One Pace][56-59] Baratie 06 [1080p][757AF173].mkv
├── ...
```

I can see that I have different episode codes from your example in the README, but I don't think that matters(?). So I wonder if this has something similar to issue #7 where I have downloaded new episodes and updated episodes from [One Pace](https://onepace.net/).

Screenshots: (Not mine, but it shows exact same)

First click:
![Screenshot showing first message.](https://user-images.githubusercontent.com/6759280/184575792-ea85717f-2341-4b66-a56c-f1331041ee89.png)
After clicking cancel:
![Screenshot showing second message.](https://user-images.githubusercontent.com/6759280/184575813-06b3a0da-2152-4314-a326-d851afdbe2f4.png)

Also One Pace have added new arc cover images with the 2.5 update.

**Comment by jwueller** [comment]
That's very strange and I can't currently explain this behavior. The plugin doesn't touch media playback at all. Could you try it without the plugin to see if it makes a difference?
